### ISSUE TITLE
Rendering out data into flat files

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#17]
Our current users (list of [known users](https://docs.google.com/spreadsheets/d/16pqZAI8pnHM_ahDyajkZuctQHPHJt_nbdudmple2gLg/edit#gid=0), though there are others, such as Eric Schmidt in Slack) are consuming the output data reports (dist.csv, dist.json, etc).  I'm not sure which items are actually in regular use, unfortunately.

We should provide the data in the same reports, at least for a while.

**Comment by lazd** [comment]
I thought about it and I don't think we can do all of the existing formats with an API endpoint. Some of these files are 100mb. We should probably generate them and push them out to a CDN.

**Comment by ryanblock** [comment]
@lazd that's exactly right. I will be working on a batch job 1-2x per day that will assemble all data, render it to a file, and publish it to S3.

Working backwards from that objective:
- All our data has to be in the database
- Which means all our scrapers need to be ported to sources
- And our cache needs to be migrated

**Comment by ryanblock** [comment]
(But to be clear, we should offer this data in endpoints as well for developers – so multiple formats. Same predicates above apply though.)

**Comment by lazd** [comment]
@ryanblock says flat file generation is a batch job:

- Collects data from DB
- Reformats data
- Dumps file into S3
- Is behind a CDN

**Comment by jzohrab** [comment]
Work-in-progress - https://github.com/covidatlas/li/pull/242

**Comment by jzohrab** [comment]
We have a job running to generate files now in prod.  We haven't cut over yet, but we're getting closer.
