### ISSUE TITLE
Port CDS `scrapers` to Li `sources`

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/li#2]
In Li, what used to be called `scrapers` are now called `sources`, and they live in `src/shared/sources`

The shape has changed, but the core scraper logic should largely remain the same. The new source shape needs docs. All sources have a simple unit test validation pass prior to commit (see below).

### Example sources
- simple: https://github.com/covidatlas/li/blob/master/src/shared/sources/us/ca/san-francisco-county.js
- less simple: https://github.com/covidatlas/li/blob/master/src/shared/sources/us/ut/index.js
- timeseries: https://github.com/covidatlas/li/blob/master/src/shared/sources/nyt/index.js
- multi-source timeseries: https://github.com/covidatlas/li/blob/master/src/shared/sources/nl/index.js

### Current shape validated here
- https://github.com/covidatlas/li/blob/master/tests/unit/shared/sources/source-validation-test.js

### Migration status

`npm run migration:status` gives a report:

```
MacBook-Air:li jeff$ npm run migration:status

> li@0.0.0 migration:status /Users/jeff/Documents/Projects/li
> node tools/report-migration-status.js

Getting commits in /Users/jeff/Documents/Projects/coronadatascraper/src/shared/scrapers for 156 files from covidatlas/coronadatascraper.git/master ...
... done.
Getting commits in /Users/jeff/Documents/Projects/li/src/shared/sources for 10 files from covidatlas/li.git/master ...
... done.


========================================

key                           CDS path                         li?  up-to-date?
---                           --------                         ---  -----------

DONE (7)
--------
au                            AU/index.js                      yes  yes 
gb-sct                        GB/SCT/index.js                  yes  yes 
in                            IN/index.js                      yes  yes 
...

NEEDS UPDATING (0)
------------------

REMAINING (149)
---------------
at                            AT/index.js                      no   -   
au-act                        AU/ACT/index.js                  no   -   
...
```

### Notes
- Small supporting datasets are ok (example: https://github.com/covidatlas/li/blob/master/src/shared/sources/nl/mapping.json), but mocks/fixtures etc. should not come over to `src/shared/sources`
- If large additional vendored datasets are needed for geo, please let me know and we'll figure out the best approach
- Helper functions: thus far in the order of keeping things as light and tidy as possible, I'm only bringing over necessary helper functions needed on a case by case basis
  - Please be judicious about what helpers you're proposing porting over
  - What you do port, please ensure it's tested
- Each `scrape` function should be sync; an async `scrape` function is likely an antipattern, and should be justifiable
- `scrape` functions should not call to the internet for anything; if they need to, please let me know and we'll figure out how to make that generic
- `scrape` functions should not have unique external dependencies; again, if they need to, please let me know and we'll figure out how to make that generic

We may want to run our existing scrapers through a script to parse, move things around, and output with something like [escodegen](https://github.com/estools/escodegen); if so, please do not put those files into `src/shared/sources` – that is the production sources directory, and only known (or expected)-working sources should live there.

**Comment by jzohrab** [comment]
Docs:

* [Migration Status spreadsheet](https://docs.google.com/spreadsheets/d/1QSzfEZHUvmh16HbyrY6DyW_ukEDA3x0esO_Fq2xgeOA/edit#gid=2137509564)
* [Guide for migrating scrapers](https://docs.google.com/document/d/1ITPU0hESswmiWw88Pl1eI26oIQtMJw1YUeD8mWEPIeE/edit#)

**Comment by jzohrab** [comment]
I'm going to mark this as done.  There are a handful of "deprecated" items on the spreadsheet, but I think that's a valid statement.  If someone would like to fill in any holes, they are welcome to.  Cheers, z
