### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/li#21]
Added a number of linting updates today to help firm up a few basic code standards:
- https://github.com/covidatlas/li/commit/dabbec30e849ad453045da6920375518ce506acc
- https://github.com/covidatlas/li/commit/6241774d4e11a07f6983ebb02106fc5fc9afe622
- https://github.com/covidatlas/li/commit/180c64156eea745c8ebc23c68c0716845b2c446e
- https://github.com/covidatlas/li/commit/6b4a0d7f7ebfa9f6f49134328f48e91a223d1008

As I've mentioned, I'm totally open to selectively and deliberately adding additional linting rules to our codebase. (I'm less open to adding large linting sets that will slow down linting operations and frustrate whitespace / linebreaks, etc.)

Please do some ideas of things we like and want to keep, please!

**Comment by jzohrab** [comment]
Perhaps we can close this.  The linting right now is unobtrusive and quick.  Thoughts?
