### ISSUE TITLE
Pending county causes error for us-ia on 4/18 and later

### ISSUE THREAD

**Issue by andys1376** [covidatlas/li#212]
* **Source: ** us-ia
* **File: ** https://opendata.arcgis.com/datasets/6a84756c2e444a87828bb7ce699fdac6_0.csv
* **Issue: ** File has row with county of "Pending County" or "Pending Investigation" starting on 4/18, which gives errors like the following:
```
us-ia error: Error: Could not associate county with FIPS code: {
  "county": "Pending Investigation County",
  "cases": 1,
  "deaths": 0,
  "recovered": 0,
  "country": "iso1:US",
  "state": "iso2:US-IA"
}
```

**Comment by jzohrab** [comment]
@andys1376 , perhaps we can give those to "UNASSIGNED".  There are a few scrapers that use unassigned already (it's defined in constants, I think).  It's good to have the numbers in there, but if they cause fips problems that's no good.  Good catch and thanks for the issue!

**Comment by jzohrab** [comment]
Fixed!
