### ISSUE TITLE
Create a processTimeseries function to avoid repeating logic for timeseries dates 

### ISSUE THREAD

**Issue by lazd** [covidatlas/li#222]
**Description**

Right now, we repeat logic for checking if a date exists in a timeseries source. NYT, JHU, everyone's logic is similar.

**Describe the solution you'd like**

processTimeseries(dateColumn, scrapeDate, processFn)

**Describe alternatives you've considered**

Hand coding the same bugs 4 times.

**Comment by jzohrab** [comment]
Can't do this exactly as specified, but I did create a `src/shared/sources/_lib/timeseries-filter.js` function which I'm using in a few places so far.  It works well.  Docs are in that source file, and tests are in unit tests.
