### ISSUE TITLE
Gather current data consumer feedback on what data they're actually using

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#233]
We have several data consumers, but with the transition from CDS to Li the generated reports may change, impacting them.  We may not have to worry about some changes though, so gather some information about what data they're using.

Email sent to consumers:

---

Hello,

I'm part of the Covid Atlas team (what used to be called Corona Data Scraper).  I wanted to let you know of some changes in our project which may impact you, and see if you're available and interested to give us feedback on these changes.

You may have an app, or be doing some analysis, which relies on the flat files of Corona Data Scraper, currently available at https://coronadatascraper.com/#home.  We are transitioning to a new project architecture for crawling and scraping data (the new project repository is https://github.com/covidatlas/li/).  We intend to continue to generate flat files for the data, and will try to port most of the current structure over; however, the source URLs will likely change, and the report structure or information may change as well.

We want to minimize the impact this may have on you.  If you're no longer using our data, please let me know!  But if you are, we'd appreciate it if you could let us know the following to help us limit the report migration scope:

- which files you're working with
- which fields you're referring to in each file

You can either reply to this email, or drop a comment in GitHub issue https://github.com/covidatlas/li/issues/233.

In addition, if you are interested, it would be great if you could work with us on the reports as we generate them as well -- either trying some mods to your apps as we release draft versions, or simply spot-checking the data for us.  This feedback will help us create new data quality monitoring tools, which are sorely lacking.

In the future, we will also be releasing a v1 API to access our data, and will solicit feedback for our RFC.  Let me know if you're interested.

**Comment by jzohrab** [comment]
I've sent an email to the consumers whose addresses I currently have on file.

**Comment by jzohrab** [comment]
Pinging @microprediction and @heatxsink -- I didn't have your emails or see you on our Slack, so hopefully you'll see this message and let me know what data you need from us, so we can be sure it's included in our migration (or at least, try our best to include it).  Cheers! jz

**Comment by microprediction** [comment]
Thanks, Ack message. Will reply this w/kend

**Comment by Akuukis** [comment]
@jzohrab Hi, [Pandemic Estimator](https://pandemic-estimator.net/) uses API [here](https://github.com/Akuukis/pandemic-estimator/blob/abbd1533094075e7959f8ebeaf3ad274209c770b/src/stores/LocationStore.ts#L126). I've abandoned it but it still works on it's own.

If the changes are simple renames of endpoint or some props then I have no problems with it, just let me know.

**Comment by joliss** [comment]
Thanks for the heads-up! For [corona-cases.org](https://www.corona-cases.org/) I'm as of yet only using the following fields, and I'm also not fussed about changes.

```
// locations.json
locationsJson[i].countryId
locationsJson[i].stateId
locationsJson[i].countyId
locationsJson[i].city
locationsJson[i].name

// timeseries.json
timeseriesJson['YYYY-MM-DD'][i].cases
```

**Comment by roboton** [comment]
thanks for all the great work. i use the following:

aggregate
level
country
state
county
city
population
population_density
deaths
cases
tested
active
recovered
dates
geo-json

**Comment by microprediction** [comment]
Go ahead. All good here. Nothing critical my end.

**Comment by heatxsink** [comment]
Ack. I've taken your location.json and made my own abomination! Thus any change on your end will not effect my site.

**Comment by igorkofman** [comment]
Hey folks, CAN uses:

cases
tested
icu_current
hospitalized_current

**Comment by jzohrab** [comment]
Email from Ryan Cooper: "Thanks for the heads up. I developed a Shiny data visualization app in R that uses the **CSV tidy format**. I will take a look at the new git repo and update paths accordingly. The app uses USA data only and it incorporates all available metrics. I'll provide feedback if I see any issues. Thanks for the project. Keep me in the loop."

Email from David Kulp: "I use **timeseries.csv and use city,county,state,country,population,date,cases,deaths,and tested columns**."

**Comment by jzohrab** [comment]
Email from David Edwards:

---

My project currently uses two flat files from the Corona Data Scraper website.

* https://coronadatascraper.com/timeseries-byLocation.json
* https://coronadatascraper.com/timeseries-jhu.csv

Primarily we are using the “dates" object in timeseries-byLocation.json to generate charts. Changes to the format of the location names in that file would be impactful as well.

We only use the jhu CSV internally to generate a weekly ranking by location.

Details about the project are available here… https://routinehub.co/shortcut/4867, 
"Coronavirus Curve Graph the trend of COVID-19 cases for over 4,000 locations."

**Comment by jzohrab** [comment]
Hi @roboton, can you let me know which reports/files you're using?  Are you referring to

https://coronadatascraper.com/#data.json 
https://coronadatascraper.com/#timeseries-byLocation.json

I suspect it's the latter, but would like to be sure.  Thanks! jz

**Comment by roboton** [comment]
Yup it's the latter as well as features.json (the geojson data)

Thanks JZ!

**Comment by rtwfroody** [comment]
I've got a simple site at http://casualhacker.net/covid19

It fetches https://coronadatascraper.com/timeseries.csv hourly, and uses fields:
* country
* state
* county
* city
* population
* cases
* deaths
* recovered
* tested
* date

Thank you!

**Comment by jzohrab** [comment]
Hi all, I'll be sending another message out soon about progress in this area.  Heads up there are some very minor changes to the reports, which I hope are not impactful -- and if there are, we can make some adjustments.  Thanks again! jz
