### ISSUE TITLE
Reports failing on generation (presumably out of memory)

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#264]
https://api.staging.covidatlas.com/report_status currently shows the following:

```
[
  {
    "updated": "2020-06-30T10:02:38.057Z",
    "report": "timeseries-jhu.csv",
    "status": "success"
  },
  {
    "updated": "2020-06-30T10:02:38.062Z",
    "report": "timeseries-tidy.csv",
    "status": "generating"
  },
  {
    "updated": "2020-06-30T10:02:28.555Z",
    "report": "locations.json",
    "status": "success"
  },
  {
    "updated": "2020-06-30T09:59:10.076Z",
    "report": "timeseries.csv",
    "status": "pending"
  },
  {
    "updated": "2020-06-30T10:02:27.197Z",
    "report": "baseData.json",
    "status": "success"
  },
  {
    "updated": "2020-06-30T10:02:30.635Z",
    "report": "timeseries-byLocation.json",
    "status": "success"
  }
]
```

If one report is "generating" and another is "pending" that means they timed out.

# Possible changes

The current implementation is naive: it’s looping through all locations, querying (and blocking) for each, and putting timeseries together for each … currently that’s 2500+ queries sent sequentially, and it may be rather slow.

Maybe we could come up with some ideas on how to improve it.  We could presumably do one of the following:

## Changing how queries are run

(These are both sticking within the current design.)

a) query locations in batches (like query table where locationID in ('x', 'y', 'z') etc)
b) do an async pool of queries and processing, so that several queries can be dispatched at once
c) change the implementation so that it just does a full scan({}) of the dynamo table, and then processes each record, rather than querying and sorting.  This would be more complicated, it’s a big change from the current implementation.

## 2. Go with a more involved map-reduce, using several lambdas.

Maybe better?, would be to actually do more map-reduce with multiple lambdas, so we break the problem into smaller subsets which run independently, posting them to s3, and then reduce them into the final dataset.  This would be an interesting thing to try out, and uses the power of lambda, but I don’t know if we’d hit any lambda throttling (instance count etc).

## 3. different data indexing?

Last idea: maybe we can add another global secondary index to the case-data table, on the date, so that we can query by date, b/c there will be fewer dates to build the report than there are locations.

**Comment by jzohrab** [comment]
Looks like it failed on timeseries-tidy.csv.  Not surprising as that report must be large (it repeats the base data for each field of case data, and then prints the type of case data, and the value.

Looking at cloudwatch logs (https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FLiStaging-Reports-NJ9FSKO2NXAE/log-events/2020$252F06$252F30$252F$255B$2524LATEST$255D707212db206243e9a0c7d44dca531cff$3Fstart$3DPT3H)

```
2020-06-30T09:53:33.211Z	ff65deac-bd0c-44db-8351-e6151e329d1a	INFO	Report timeseries-byLocation.json: pending
2020-06-30T09:53:36.213Z	ff65deac-bd0c-44db-8351-e6151e329d1a	INFO	Report baseData.json: generating (1 of 2684)
2020-06-30T09:56:49.455Z	ff65deac-bd0c-44db-8351-e6151e329d1a	INFO	Report baseData.json: generating (2681 of 2684)
```

3 mins to generate baseData.json -- that's not bad at all.

```
2020-06-30T09:56:49.638Z	ff65deac-bd0c-44db-8351-e6151e329d1a	INFO	Report locations.json: generating
...
2020-06-30T09:56:50.552Z	ff65deac-bd0c-44db-8351-e6151e329d1a	INFO	Report locations.json: success
```

other reports also good and fast ...
timeseries-byLocation.json
timeseries-jhu.csv

But it fails on timeseries-tidy.csv

```
2020-06-30T09:56:59.598Z	ff65deac-bd0c-44db-8351-e6151e329d1a	INFO	Report timeseries-tidy.csv: generating
2ND RequestId: ff65deac-bd0c-44db-8351-e6151e329d1a
REPORT RequestId: ff65deac-bd0c-44db-8351-e6151e329d1a	Duration: 232469.26 ms	Billed Duration: 232500 ms	Memory Size: 256 MB	Max Memory Used: 256 MB
RequestId: ff65deac-bd0c-44db-8351-e6151e329d1a Error: Runtime exited with error: signal: killed
Runtime.ExitError
```

**Comment by jzohrab** [comment]
In https://coronadatascraper.com/#home, timeseries-tidy.csv is about 250MB uncompressed, and 6MB compressed.

All file sizes from that URL:

```
total 764240
-rw-r--r--@ 1 jeff  staff    32M Jun 30 07:50 timeseries-byLocation.json
-rw-r--r--@ 1 jeff  staff   2.5M Jun 30 07:51 timeseries-jhu.csv
-rw-rw-r--@ 1 jeff  staff   236M Jun 29 22:02 timeseries-tidy.csv
-rw-r--r--@ 1 jeff  staff   6.6M Jun 30 07:48 timeseries-tidy.csv.zip
-rw-r--r--@ 1 jeff  staff    83M Jun 30 07:51 timeseries.csv
```

**Comment by jzohrab** [comment]
Working on this in wip-write-timeseries-tidy-to-zipped-file.

**Comment by jzohrab** [comment]
Pushed that branch, works for local and for my small tests connecting to a test s3 bucket.  Will launch to staging and check.

**Comment by jzohrab** [comment]
Now not failing due to memory, but due to timeout for the same report.  It's timing out after **12 minutes** on that report, which is a silly amount of time to be spending.  Though the report is large-ish, I'd expect it to write out to disk fairly quickly, and upload should be reasonable.  I'll try changing it to disk-write-then-upload. 

https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FLiStaging-Reports-NJ9FSKO2NXAE/log-events/2020$252F07$252F01$252F$255B$2524LATEST$255De23eda9924754d379fa6cfe56cbe60ee$3Fstart$3DPT3H

```
2020-07-01T16:16:34.659Z	8f29253a-4616-4961-918b-3da41264db64	INFO	Report timeseries-tidy.csv.gz: generating

REPORT RequestId: 8f29253a-4616-4961-918b-3da41264db64	Duration: 900019.89 ms	Billed Duration: 900000 ms	Memory Size: 256 MB	Max Memory Used: 256 MB	Init Duration: 394.51 ms

2020-07-01T16:28:11.260Z 8f29253a-4616-4961-918b-3da41264db64 Task timed out after 900.02 seconds
```

The reports now stream to s3 when writing.  The reports compress before streaming, but perhaps streaming directly is causing issues.

**Comment by jzohrab** [comment]
Actually changing writing to write in batches -- currently impl is silly, writing to s3 for every single csv record, could result in multiple thousands of writes!

**Comment by jzohrab** [comment]
Hm, batching code is working in prod, but it still hits either a memory or time limit (I can't say for sure which one ... see the timestamps):

```
2020-07-01T15:49:30.769-04:00  -- 2020-07-01T19:49:30.611Z	d78e8afc-0c56-4e15-aa56-77b0d87ee2ca	INFO	timeseries-tidy.csv: batch 247 of 269

## Note this is 15:58, prev was 15:49 ... 9 mins lost somewhere?

2020-07-01T15:58:32.620-04:00 -- END RequestId: d78e8afc-0c56-4e15-aa56-77b0d87ee2ca

2020-07-01T15:58:32.620-04:00 -- REPORT RequestId: d78e8afc-0c56-4e15-aa56-77b0d87ee2ca	Duration: 898063.36 ms	Billed Duration: 898100 ms	Memory Size: 256 MB	Max Memory Used: 257 MB	Init Duration: 398.64 ms
```

**Comment by jzohrab** [comment]
Same issue happened a few times in a row ... it reaches approx batch 246 of 269 in timeseries-tidy.csv.gz, hangs for ~8 mins, and then fails.  Changing to write file locally, and then ship to s3.

**Comment by jzohrab** [comment]
Same issue, even when writing locally and then uploading.  No idea why -- should really add memory profiling ... anyway, have maxed out the memory for the lambda now (was 256 MB, now is 3008 MB), and if it fails again, I'll consider vastly simplifying, or even pulling, timeseries-tidy.csv.  Even if it passes, I may pull it, depending on how much time it takes to generate, b/c it's too fragile to have it kill everything.

**Comment by jzohrab** [comment]
Getting closer.  timeseries.csv is 0 bytes.  All other reports are present though, including the massive one.  So I'll try a different method for writing this out.

**Comment by ryanblock** [comment]
Same q as in the other PR, why write to disk at all? Send the buffer directly to s3, I see no reason to persist to disk, and many reasons not to.

**Comment by jzohrab** [comment]
@ryanblock - same answer as the other PR.  I've been working on this for a while, and tried to send a stream directly to S3, but it was failing at the time.  I may try again with streams.  I've been looking at how to write to buffers but am not sure I get the ins and outs for node.  If you can provide a working example I'll gladly change everything over.

**Comment by jzohrab** [comment]
Reports generated successfully on staging, https://s3.console.aws.amazon.com/s3/buckets/listaging-reportsbucket-1bjqfmfwopcdd/beta/latest/?region=us-west-1&tab=overview.

```
$ ls -l
total 130144
-rw-r--r--@ 1 jeff  staff  10376495 Jul  3 23:52 baseData.json
-rw-r--r--@ 1 jeff  staff   2749765 Jul  3 23:52 locations.json
-rw-r--r--@ 1 jeff  staff   9794292 Jul  3 23:52 timeseries-byLocation.json
-rw-r--r--@ 1 jeff  staff    880283 Jul  3 23:52 timeseries-jhu.csv
-rw-r--r--@ 1 jeff  staff  32222870 Jul  3 23:54 timeseries-tidy.csv
-rw-r--r--@ 1 jeff  staff   1048506 Jul  3 23:53 timeseries-tidy.csv.gz
-rw-r--r--@ 1 jeff  staff   9548695 Jul  3 23:53 timeseries.csv
```
