### ISSUE TITLE
Validate generated report content

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#272]
Our report code is currently generating some files to staging/beta/latest (https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest), and these files need to be verified.  These reports are replacements for those listed in https://coronadatascraper.com/#home, and should be approximately equal, though some have changed slightly (see ./docs/reports.md).

## baseData.json

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/baseData.json

This is the base data that's used for all subsequent reports.

It should have ~2600 locations.  The locations should have timeseries data starting at, say, March 2020, and ending today/yesterday.  Because some of our scrapers are currently broken (see https://api.staging.covidatlas.com/status?format=html), we won't have everything.

## locations.json

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/locations.json

This should contain the same location IDs as baseData.json, ~2600 locations.

## timeseries-byLocation.json

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/timeseries-byLocation.json

This should contain the same locations, and same timeseries data.

## timeseries-jhu.csv

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/timeseries-jhu.csv

This should contain all locations, and all the dates as column headings, with the case data for each location.

## timeseries-tidy.csv (zipped)

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/timeseries-tidy.csv.gz

This unzipped report should be extremely large, I'm wondering if something has dropped off from it.  It should contain every single location-date-number combination for all fields.  E.g., for a given location X that has 20 deaths on date D1, and 30 deaths and 10 cases on date D2, the file should look like this:

X  D1  deaths  20
X  D2  deaths  30
X  d2  cases   10

Currently, this file is only about 1 MB zipped, and 30 MB unzipped.  In Coronadatascraper.com (aka CDS), timeseries-tidy.csv.zip is 7.5 MB, and the unzipped file is ~250 MB ... _much_ bigger!  I haven't checked the CDS report, and it may have some problems, but I would think it's ok.

## timeseries.csv  ( << this is currently broken, I'm working on it! )

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/timeseries.csv

**Comment by joliss** [comment]
Looking at Li's `timeseries-byLocation.json` file, some of the JSON structure seems to have changed: The top level is no longer a mapping from human-readable name to object, but rather an array of objects. Also, the `"dates"` field is now called `"timeseries"`.

I'm assuming we'll want the files to look exactly same (or at least as similar as possible), so that it's easy to compare them for validation, and so that consumers don't have to be updated. If we want to change the format, it's perhaps easier to also generate a second file with the new format, and deprecate the `timeseries-byLocation.json` file (while keeping it around as long as we can).

I'd ideally just like to dig into the generator code and fix this myself; perhaps you can show me around in the codebase tomorrow?

**Comment by jzohrab** [comment]
Hi @joliss - I think that some of those changes were intentional :-) but calling the field `dates` is no problem.  Maybe some other things will need to be changed at well if we call it that.  Everything there was my idea, we can def. make changes.  There's decent test coverage (unit and integration), enough so that I'm not stressed about changes at all.  We'll also need to update documentation, and somehow alert consumers of the changes as we go.

I'm in Toronto time zone, we could try doing a walkthrough on Slack.  What time works for you?

**Comment by jzohrab** [comment]
Have started this in draft PR #298, analyzing dates present in the data.

**Comment by jzohrab** [comment]
I've been receiving feedback on the data from users in another issue ... with fixes we now have all the dates and all the locations.  I can't guarantee that the numbers are any good, though!  We have data, but without a big-picture view of what the numbers look like, I'm not sure how to validate things.  @joliss , your data viewer looked really good -- perhaps we can review that and see how to join forces with your work.  Also, we have the covidatlas.com site itself, which has graphs -- I'm not sure which direction to take to validate what we have.

**Comment by jzohrab** [comment]
I believe this is done ... we have other issues open for data quality monitoring, and I may draft some ideas about other things we can check.
