### ISSUE TITLE
(unassigned) county results in error

### ISSUE THREAD

**Issue by lazd** [covidatlas/li#28]
## Description

When returning something like:

```
{
  "county": "(unassigned)",
  "cases": 3,
  "deaths": 0,
  "country": "iso1:US",
  "state": "iso2:US-VT"
}
```

The following error happens:

```
Error: Failed to scrape us-vt
    at scrapeSource (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/index.js:73:11)
    at async /Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/node_modules/@architect/functions/src/events/subscribe.js:28:18
    at async Promise.all (index 0)
    at async lambda (/Volumes/lazdRAID/Users/lazdHome/repos/li/src/events/scraper/node_modules/@architect/functions/src/events/subscribe.js:25:14)

❌ Failed to scrape us-vt: 
 Error: Could not associate county with FIPS code: {
  "county": "(unassigned)",
  "cases": 3,
  "deaths": 0,
  "country": "iso1:US",
  "state": "iso2:US-VT"
}
```

**Comment by ryanblock** [comment]
Gotcha! See: https://github.com/covidatlas/li/blob/master/src/events/scraper/normalize-data/_normalize-us.js#L62-L65

You want this issue or shall I?

**Comment by lazd** [comment]
@ryanblock you can take it!

**Comment by lazd** [comment]
Note also #30, and the value should be `(unassigned)` so it's clearly an identifier and not the name of a county.

**Comment by ryanblock** [comment]
Not sure I track, are we concerned that there may be a county out there named `Unassigned County` that may conflict?

**Comment by lazd** [comment]
We're currently using `(unassigned)`, we should continue using `(unassigned)` as users of our dataset may expect that. Additionally, the syntax clearly implies that it's not a real county name.

**Comment by ryanblock** [comment]
Thanks for adding the `unknown` case back – I think we were crossing streams in Slack when we discussed.

Some sources return counties with `(unassigned)`, as they did in CDS. `unknown` was there because that's how the NYT dataset refers to what we otherwise call `unassigned`.

Looks like we've now covered our most common cases!
