### ISSUE TITLE
Lots of data missing between 2020-05-30 and 2020-06-21

### ISSUE THREAD

**Issue by rtwfroody** [covidatlas/li#294]
* **Source: ** https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/timeseries-byLocation.json
* **Issue: ** Every(?) location is missing data between 2020-05-30 and 2020-06-21.

```
...
    "locationID": "iso1:us",
...
    "timeseries": {
...
      "2020-05-30": {
        "cases": 1728719,
        "deaths": 101431,
        "growthFactor": 1.01
      },
      "2020-06-21": {
        "cases": 2269455,
        "deaths": 113749,
        "tested": 27086984,
        "growthFactor": 1.31
      },
...
```

**Comment by jzohrab** [comment]
Thanks, I generated https://docs.google.com/spreadsheets/d/1Xeq7nJdEbXtYpDR9LlXva2pZJfjNJtonDn7vSKuTFX0/edit?usp=sharing from the data and saw a bunch of gaps.  Cheers, will start looking into it.

**Comment by jzohrab** [comment]
I've confirmed what you posted, thanks again for the heads up.  The reports were generated from our staging site, and for some reason, we're missing data in our dynamoDB in staging between those dates.  I've checked production and all of the dates are present in dynamoDB, so I'll promote the report code to production, regenerate, and will check the data consistency before sending out new URLs.

I'm ... disappointed ? ... that we're missing data in our staging site, but then again, staging isn't prod!  Cheers, will update tomorrow, or shortly.

**Comment by jzohrab** [comment]
Have launched report generation code to prod, will check prod bucket reports later to see if all generated ok.  Bucket name: liproduction-reportsbucket-bhk8fnhv1s76

**Comment by jzohrab** [comment]
File has been generated to the production bucket: s3://liproduction-reportsbucket-bhk8fnhv1s76/beta/latest/timeseries-byLocation.json

I checked one of the locations that was missing data in staging (`iso1:at#iso2:at-1`), and the data for all dates is present.  If you check the coverage report (see "PRODUCTION timeseries-byLocation-dates" tab in [this google sheet](https://docs.google.com/spreadsheets/d/1Xeq7nJdEbXtYpDR9LlXva2pZJfjNJtonDn7vSKuTFX0/edit#gid=1895621508) ), you'll see that most dates are present.

We still need more checks, but I believe this can be closed.  @rtwfroody , do you agree?

**Comment by jzohrab** [comment]
I've opened a separate issue for data missing prior to 2020-05-23, https://github.com/covidatlas/li/issues/302.

**Comment by rtwfroody** [comment]
The data looks good now. Thanks.
