### ISSUE TITLE
Lots of spurious file change events

### ISSUE THREAD

**Issue by joliss** [covidatlas/li#301]
/cc @ryanblock 

So I was trying to figure out why rehydration is taking so long for me (30 seconds), and from the profiler it's looking like it's spending most of the time handling a flood of `FSWatcher._handle.onchange` events. Digging into why I'm seeing so many onchange events, it turns out that hydration is causing a lot of files to somehow get touched (or otherwise register as changed), which then floods the watcher with onchange events. This is happening on Ubuntu 20.04 on an XFS filesystem.

Here's what I'm doing to reproduce this:

```
~/src/li $ cat node-watch-test.js
let watch = require('node-watch')
let watcher = watch('.', { recursive: true })
watcher.on('change', function (event, fileName) {
    console.log(event, fileName)
})
```

If in one window I run

```
~/src/li $ node node-watch-test.js > ~/watch
```

and in another

```
~/src/li $ npm start
```

then I get the following output in `~/watch`: https://gist.github.com/joliss/3ac7a9fe64ca35927f25d5dcb786ac55

So now I have two questions:

1. Can you reproduce this? I'm wondering if maybe this is happening even on macOS or Windows, but those platforms just do a better job coalescing onchange events, so they don't suffer the performance penalty that I'm observing on my system.

2. Any ideas what might possibly be causing all those file change events to happen?

**Comment by jzohrab** [comment]
Hi @joliss - I'll take a look on my Mac.  Maybe we should also open up this issue in the Architect repo - main org is at https://github.com/architect, hydrate is https://github.com/architect/hydrate.

**Comment by jzohrab** [comment]
Reproduced on a mac, same watcher file as you:

```
$ cat node-watch-test.js 
let watch = require('node-watch')
let watcher = watch('.', { recursive: true })
watcher.on('change', function (event, fileName) {
    console.log(event, fileName)
})
```

and `npm start` in a separate window creates a huge file:

```
$ cat ~/watch | wc -l
   10022
```

Checking the `hydrate` architect project.

**Comment by ryanblock** [comment]
I fix (of sorts) for this may already be available in Sandbox 1.13.0. Just to be sure, you’re running hydrate while sandbox is running?

**Comment by joliss** [comment]
Yes, it's the (initial, and re-)hydrate started by the sandbox process, if I understand it correctly.

**Comment by ryanblock** [comment]
The initial hydration happens before the filesystem water kicks up.

Out of curiosity, do you recall why you were running hydrate after the sandbox already started? May help better understand the use case.

**Comment by joliss** [comment]
I'm just running `npm start`. The script I posted above shows that a lot of files are being touched during hydration – this happens both during initial hydration and during rehydration (after I `touch` a random file). Of course, it's less of a problem during initial hydration when the watcher hasn't been started yet, but it seems to be the cause of the performance degradation I'm seeing during rehydration.

**Comment by ryanblock** [comment]
Ok, let's move this over to https://github.com/architect/architect/issues/908 since this is a framework concern not a Li-specific concern.
