### ISSUE TITLE
Scraper status slack bot

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/li#33]
And we should escape colons because things like "iso1:SA: Error:" will turn :SA: into an emoji (🈂️)

**Comment by ryanblock** [comment]
I am very much looking forward to building this! (As you may or may not know, I have some experience building Slack apps!)

**Comment by jzohrab** [comment]
I think this is high priority, it's too easy to forget to check the status pages.  We can probably just print a brief summary of sorts, listing the sources that are failing and perhaps for how long, and give a link to direct people to the status page (e.g. https://api.covidatlas.com/status?format=html).  We could potentially also ping the maintainers ... and make that a configurable option in their _lib/maintainers.js file.  Or something. :-)

**Comment by jzohrab** [comment]
Merged #573 which starts this, good enough.  Keeping this open until I see it works.  TODOs:

[ ] ensure it works
[ ] launch to prod
[ ] remove the env var in staging - `arc env remove staging SLACK_STATUS_HOOK`
[ ] ensure it works in prod

**Comment by jzohrab** [comment]
Works, done.
