### ISSUE TITLE
timeseries-byLocation.json not updated

### ISSUE THREAD

**Issue by rtwfroody** [covidatlas/li#348]
* **Source: ** https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/beta/latest/timeseries-byLocation.json
* **Issue: ** Last entry in this file is for July 22.

Did it move to a different URL?

**Comment by jzohrab** [comment]
Sorry about that @rtwfroody , they did move to v1:

https://listaging-reportsbucket-1bjqfmfwopcdd.s3-us-west-1.amazonaws.com/v1/latest/timeseries-byLocation.json.

I haven't launched it to prod yet, am still working through some front-end issues with the covidatlas site.

I'll update the main ticket!

**Comment by rtwfroody** [comment]
Thanks. That works. (Still showing #343 and #346.)

**Comment by jzohrab** [comment]
Yes, those are still outstanding issues.  :-(  Cheers! z
