### ISSUE TITLE
Add S3 integration

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/li#5]
In `staging` + `production`:
- `crawler` should write cache data to S3
- `scraper` should read cache data from S3

Locally:
- `crawler` should write cache data locally
- `scraper` should attempt to read cache data from S3, and fall back to local data sources

**Comment by jzohrab** [comment]
I believe this is done, I don't see any S3 things in `$ npm run todos`.

**Comment by ryanblock** [comment]
Done!
