### ISSUE TITLE
MT source may be dead

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/li#520]
There are missing days in the cache and the case count is not increasing:

![image](https://user-images.githubusercontent.com/26465923/79616807-c83dff00-80ba-11ea-93b2-4f16c47414cd.png)

**Comment by jzohrab** [comment]
us-mt best handled via arcgis url:

https://services.arcgis.com/qnjIrwR8z5Izc0ij/ArcGIS/rest/services/COVID_Cases_Production_View/FeatureServer/0/query

That is the feature server that appears to be called by their "official map" - https://montana.maps.arcgis.com/apps/MapSeries/index.html?appid=7c34f3412536439491adcc2103421d4b.

**Comment by jzohrab** [comment]
Updated. merged into master.
