### ISSUE TITLE
Add scraper for Hungary

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/li#538]
## Location name

Hungary

## Source URL

https://docs.google.com/spreadsheets/d/1e4VEZL1xvsALoOIq9V2SQuICeQrT5MtWfBm32ad7i8Q/edit#gid=311133316

## Notes/comments

Entered daily from the official government website, which uses images.

**Comment by jzohrab** [comment]
The "megyei" sheet doesn't have all of the states (e.g. it's missing Sopron (iso2:HU-SN)), but it has many of them.  Opening a PR :-)

**Comment by jzohrab** [comment]
Opened https://github.com/covidatlas/li/pull/560, @hyperknot can you take a peek?  It gets the data ok, but doesn't seem to cover all the states.

**Comment by jzohrab** [comment]
Note from the spreadsheet maintainer:

> Thank you for your request. Yes, you can reuse and scrape the data. Because we have now relatively few cases we update the dataset on a weekly base, every Monday. If the new cases would grow again, we put back the daily update. I see your comment on Github regarding Sopron. Sopron is not county and not county capital, what you need for that county is Győr-Moson-Sopron column. All the Hungarian counties we have (19), + the capital Budapest. Unfortunately we don't have detailed, more accurate data for smaller administrative units since the government does not disclose them.
