### ISSUE TITLE
Generalize parsing patterns

### ISSUE THREAD

**Issue by lazd** [covidatlas/li#558]
Many patterns are starting to emerge in the way data is stored and parsed, such as tables with left-handle labels, etc.

Though it's likely that many of these will still have to be case-by-case, they should be generalized if at all possible in `lib/parse.js` as a configurable function.

**Comment by jzohrab** [comment]
I think we're gradually moving away from scraping HTML, and we have a few lib functions here and there now.

They need better docs ... but that's a different story.  Closing, thx!
