### ISSUE TITLE
Replace ArcGIS FeatureServer with new FeatureServer for Alameda County, California

### ISSUE THREAD

**Issue by 1ec5** [covidatlas/li#562]
Alameda County, California, recently replaced their ArcGIS dashboard with a series of Power BI dashboards. So instead of a clean FeatureServer to query, we’ll have to reverse-engineer the API calls used by the Power BI dashboard, as in 1ec5/external-data-bot@dfd978d0b2cfccfef1b9490259e9080e0aa76999 covidatlas/coronadatascraper#1026.

**Comment by jzohrab** [comment]
What a drag ... isn't this much harder to work with?

**Comment by 1ec5** [comment]
[The ArcGIS FeatureServer is back](https://data.acgov.org/datasets/5d6bf4760af64db48b6d053e7569a47b_4).
