### ISSUE TITLE
Regen S3 data

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/li#66]
Some sources have changed their cache keys, so we'll need to regen their full S3 data.

The scrapers from CDS that had cache key changes were:
US/TN : default => data
US/VA : we talked about this one before, with their county names becoming cache keys, eg Some County => somecounty
US/VT : default => data

Can gen all three with:
`node tools/generate-v1-cache.js --location US/TN,US/VA,US/VT --dest zz-mig3`

**Comment by ryanblock** [comment]
Done!
