### ISSUE TITLE
Deal with slugify's stripping o with macron (ō)

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/li#85]
Until [this gets merged](https://github.com/simov/slugify/pull/76) we should manually add `ō` mappings to our slugify use.

**Comment by camjc** [comment]
Already done in `src/events/scraper/run-scraper/scraper-helpers/get-iso2-from-name.js`.
Since its a singleton it'll get used within that lambda (only place that needs it as far as I know?)
Shall we close this or theres something else to do?

**Comment by camjc** [comment]
This is merged upstream now. We can remove in the util in this repo.
