### ISSUE TITLE
Add linter to ensure all source filenames are lower case dasherized

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/li#9]
cc @camjc

**Comment by camjc** [comment]
Any reason to not just copy over the linting setup incl prettier from the other repo? Did we want to use this as an opportunity to reevaluate our rules generally? The earlier we get rules in we’re happy with the less manual work to implement them.

**Comment by ryanblock** [comment]
This is a great moment to evaluate our linting in general. Imo as with many things in life, less is more; instead of dropping in large blanket linting rulesets, I hope we can be specific and deliberate about each, and evaluate what we hope it will achieve for us.

**Comment by jzohrab** [comment]
Things I really like about CDS linting:

* tells me of unused vars, imports, functions
* != vs !== and similar
* naming conventions
* imports at the top
* string conventions
* obv syntax errors

Don't like:

* spacing and carriage returns

**Comment by ryanblock** [comment]
I’d say all the things you like are already present in the current Li linting rules. ✨
